name: PyInstaller build

on: [push]

jobs:
  build_ubuntu:
    strategy:
      matrix:
        include:
          - filename: Clangen_Linux64_glibc2.31+.tar.xz
            itch-channel: linux64_glibc_231
            os: ubuntu-20.04
            api-artifact: linux2.31
          - filename: Clangen_Linux64_glibc2.35+.tar.xz
            itch-channel: linux64_glibc_235
            os: ubuntu-22.04
            api-artifact: linux2.35
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.1
      - name: Setup Python 3.11 x64
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: "x64"
          cache: "poetry"
      - name: install dependencies
        run: poetry install --with build -E discord
      - name: Configure dev
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "VERSION_NUMBER=${{ github.sha }}" >> $GITHUB_ENV
          echo "RELEASE_CHANNEL=development" >> $GITHUB_ENV
      - name: Configure release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION_NUMBER=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_CHANNEL=stable" >> $GITHUB_ENV
      - name: Write version file
        run: |
          echo "[DEFAULT]" > version.ini
          echo "version_number=${{ env.VERSION_NUMBER }}" >> version.ini
          echo "release_channel=${{ env.RELEASE_CHANNEL }}" >> version.ini
          echo "upstream=${{ github.repository }}" >> version.ini
      # This only runs on development builds, please write release commits manually
      - name: Write commit file
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          git log --pretty="format:%H|||%cd|||%b|||%s" -15 --no-decorate --merges --grep="Merge pull request" --date=short > changelog.txt
      - name: Run PyInstaller
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: poetry run python3 -m PyInstaller Clangen.spec
        env:
          IS_RELEASE: 0
      - name: Run PyInstaller
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: poetry run python3 -m PyInstaller Clangen.spec
        env:
          IS_RELEASE: 1
      - name: Create archive (.tar.xz)
        run: tar -caf ${{ matrix.filename }} -C dist Clangen
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.filename }}
          path: ${{ matrix.filename }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        if: github.repository == 'Thlumyn/clangen'
        with:
          gpg_private_key: ${{ secrets.PACKAGESIGNKEY }}
          passphrase: ${{ secrets.PACKAGESIGNKEYPASSPHRASE }}
      - name: Upload artifact to API
        if: github.repository == 'Thlumyn/clangen'
        run: |
          gpg --output ${{ matrix.filename }}.sig --detach-sig -a ${{ matrix.filename }}
          curl -X 'POST' \
            'https://clangen.archanyhm.dev/api/v1/Update/Channels/${{ env.RELEASE_CHANNEL }}/Releases/${{ env.VERSION_NUMBER }}/Appoint' \
            -H 'X-API-Key: ${{ secrets.UPDATE_API_DEPLOY_KEY }}' \
            -H 'accept: */*'
          curl -X 'PUT' \
            'https://clangen.archanyhm.dev/api/v1/Update/Channels/${{ env.RELEASE_CHANNEL }}/Releases/${{ env.VERSION_NUMBER }}/Artifacts/${{ matrix.api-artifact }}' \
            -H 'X-API-Key: ${{ secrets.UPDATE_API_DEPLOY_KEY }}' \
            -H 'accept: */*' \
            -H 'Content-Type: multipart/form-data' \
            -F 'fileBundle=@${{ matrix.filename }}' \
            -F 'fileBundle=@${{ matrix.filename }}.sig' \
            --http1.1
      - name: Set up butler
        uses: jdno/setup-butler@v1
      - name: Upload build to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/') && env.BUTLER_API_KEY != ''
        run: butler push ${{ matrix.filename }} sablesteel/clan-gen-fan-edit:${{ matrix.itch-channel }} --userversion "${{ env.VERSION_NUMBER }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.filename }}

  build_win:
    strategy:
      matrix:
        include:
          - filename: Clangen_Win32.zip
            itch-channel: win32
            os: windows-2019
            python-version: "3.8"
            architecture: x86
            api-artifact: win32
          - filename: Clangen_Win64.zip
            itch-channel: win64
            os: windows-latest
            python-version: "3.8"
            architecture: x64
            api-artifact: win64
          - filename: Clangen_Win64_Windows10+.zip
            itch-channel: win64_10
            os: windows-latest
            python-version: "3.11"
            architecture: x64
            api-artifact: win10+
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python-version }}"
          architecture: "${{ matrix.architecture }}"
          cache: ${{ matrix.architecture == 'x86' && '' || 'poetry' }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: 1.4.1
      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: install dependencies
        run: poetry install --with build -E discord
      - name: Configure dev
        shell: bash
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "VERSION_NUMBER=${{ github.sha }}" >> $GITHUB_ENV
          echo "RELEASE_CHANNEL=development" >> $GITHUB_ENV
      - name: Configure release
        shell: bash
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION_NUMBER=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_CHANNEL=stable" >> $GITHUB_ENV
      - name: Write version file
        shell: bash
        run: |
          echo "[DEFAULT]" > version.ini
          echo "version_number=${{ env.VERSION_NUMBER }}" >> version.ini
          echo "release_channel=${{ env.RELEASE_CHANNEL }}" >> version.ini
          echo "upstream=${{ github.repository }}" >> version.ini
      # This only runs on development builds, please write release commits manually
      - name: Write commit file
        shell: bash
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          git log --pretty="format:%H|||%cd|||%b|||%s" -15 --no-decorate --merges --grep="Merge pull request" --date=short > changelog.txt
      # Example of an upx install, also requires adding "--upx-dir upx-4.0.0-win64" to the pyinst run
      #- name: Setup UPX
      #  run: |
      #    curl -L -O https://github.com/upx/upx/releases/download/v4.0.0/upx-4.0.0-win64.zip
      #    tar.exe -x -v -f upx-4.0.0-win64.zip
      - name: Build self-updater binary
        shell: bash
        run: |
          cd self_updater
          cargo build --release
          cp target/release/self_updater.exe ../resources/
      - name: Run PyInstaller
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: poetry run PyInstaller Clangen.spec
        env:
          IS_RELEASE: 0
      - name: Run PyInstaller
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: poetry run PyInstaller Clangen.spec
        env:
          IS_RELEASE: 1
      - name: Create archive (.zip)
        run: |
          cp dist/Clangen/.itch.toml dist/ 
          tar.exe -a -c -f ${{ matrix.filename }} -C dist Clangen .itch.toml
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.filename }}
          path: ${{ matrix.filename }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        if: github.repository == 'Thlumyn/clangen'
        with:
          gpg_private_key: ${{ secrets.PACKAGESIGNKEY }}
          passphrase: ${{ secrets.PACKAGESIGNKEYPASSPHRASE }}
      - name: Upload artifact to API
        if: github.repository == 'Thlumyn/clangen'
        shell: bash
        run: |
          gpg --output ${{ matrix.filename }}.sig --detach-sig -a ${{ matrix.filename }}
          curl -X 'POST' \
            'https://clangen.archanyhm.dev/api/v1/Update/Channels/${{ env.RELEASE_CHANNEL }}/Releases/${{ env.VERSION_NUMBER }}/Appoint' \
            -H 'X-API-Key: ${{ secrets.UPDATE_API_DEPLOY_KEY }}' \
            -H 'accept: */*'
          curl -X 'PUT' \
            'https://clangen.archanyhm.dev/api/v1/Update/Channels/${{ env.RELEASE_CHANNEL }}/Releases/${{ env.VERSION_NUMBER }}/Artifacts/${{ matrix.api-artifact }}' \
            -H 'X-API-Key: ${{ secrets.UPDATE_API_DEPLOY_KEY }}' \
            -H 'accept: */*' \
            -H 'Content-Type: multipart/form-data' \
            -F 'fileBundle=@${{ matrix.filename }};type=application/zip' \
            -F 'fileBundle=@${{ matrix.filename }}.sig' \
            --http1.1
      - name: Set up butler
        uses: jdno/setup-butler@v1
      - name: Upload build to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/') && env.BUTLER_API_KEY != ''
        run: butler push ${{ matrix.filename }} sablesteel/clan-gen-fan-edit:${{ matrix.itch-channel }} --userversion "${{ env.VERSION_NUMBER }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.filename }}

  build_macos64:
    # For commits to the original mac build action see:
    # https://github.com/Thlumyn/clangen/blob/29c9e39fed9a09b8de906f5c3b91dc044fe9b9a5/.github/workflows/main.yml
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11 x64
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.11"
      # - name: Install poetry
      #   uses: abatilo/actions-poetry@v2
      #   with:
      #     poetry-version: 1.4.1
      # - name: install dependencies
      #   run: poetry install --with build -E discord
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Update setuptools and wheel
        run: python -m pip install --upgrade setuptools wheel
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: Install Pillow for icon format conversion
        run: python -m pip install --upgrade Pillow
      - name: Install PyInstaller
        run: python -m pip install --upgrade PyInstaller
      - name: Configure dev
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "VERSION_NUMBER=${{ github.sha }}" >> $GITHUB_ENV
          echo "RELEASE_CHANNEL=development" >> $GITHUB_ENV
      - name: Configure release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION_NUMBER=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_CHANNEL=stable" >> $GITHUB_ENV
      - name: Write version file
        run: |
          echo "[DEFAULT]" > version.ini
          echo "version_number=${{ env.VERSION_NUMBER }}" >> version.ini
          echo "release_channel=${{ env.RELEASE_CHANNEL }}" >> version.ini
          echo "upstream=${{ github.repository }}" >> version.ini
      # This only runs on development builds, please write release commits manually
      - name: Write commit file
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          git log --pretty="format:%H|||%cd|||%b|||%s" -15 --no-decorate --merges --grep="Merge pull request" --date=short > changelog.txt
      - name: Run PyInstaller
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: python -m PyInstaller Clangen.spec
        env:
          IS_RELEASE: 0
      - name: Run PyInstaller
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: python -m PyInstaller Clangen.spec
        env:
          IS_RELEASE: 1
      - name: Create archive (.tar.xz)
        run: rm -r dist/Clangen
      - name: Install appdmg
        run: "npm install -g appdmg"
      - name: Generate .dmg
        run: "appdmg appdmg.json Clangen_macOS64.dmg"
      - uses: actions/upload-artifact@v3
        with:
          name: Clangen_macOS64.dmg
          path: Clangen_macOS64.dmg
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        if: github.repository == 'Thlumyn/clangen'
        with:
          gpg_private_key: ${{ secrets.PACKAGESIGNKEY }}
          passphrase: ${{ secrets.PACKAGESIGNKEYPASSPHRASE }}
      - name: Upload artifact to API
        if: github.repository == 'Thlumyn/clangen'
        run: |
          zip Clangen_macOS64.dmg.zip ./Clangen_macOS64.dmg
          gpg --output Clangen_macOS64.dmg.zip.sig --detach-sig -a Clangen_macOS64.dmg.zip
          curl -X 'POST' \
            'https://clangen.archanyhm.dev/api/v1/Update/Channels/${{ env.RELEASE_CHANNEL }}/Releases/${{ env.VERSION_NUMBER }}/Appoint' \
            -H 'X-API-Key: ${{ secrets.UPDATE_API_DEPLOY_KEY }}' \
            -H 'accept: */*'
          curl -X 'PUT' \
            'https://clangen.archanyhm.dev/api/v1/Update/Channels/${{ env.RELEASE_CHANNEL }}/Releases/${{ env.VERSION_NUMBER }}/Artifacts/macOS' \
            -H 'X-API-Key: ${{ secrets.UPDATE_API_DEPLOY_KEY }}' \
            -H 'accept: */*' \
            -H 'Content-Type: multipart/form-data' \
            -F 'fileBundle=@Clangen_macOS64.dmg.zip;type=application/zip' \
            -F 'fileBundle=@Clangen_macOS64.dmg.zip.sig' \
            --http1.1
      - name: Set up butler
        uses: jdno/setup-butler@v1
      - name: Upload build to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
        if: startsWith(github.ref, 'refs/tags/') && env.BUTLER_API_KEY != ''
        run: butler push Clangen_macOS64.dmg sablesteel/clan-gen-fan-edit:osx64 --userversion "${{ env.VERSION_NUMBER }}"
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Clangen_macOS64.dmg

  confirm_release_ubuntu_22_04:
    runs-on: ubuntu-22.04
    needs:
      - build_ubuntu
      - build_win
      - build_macos64
    steps:
      - name: Configure dev
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: |
          echo "VERSION_NUMBER=${{ github.sha }}" >> $GITHUB_ENV
          echo "RELEASE_CHANNEL=development" >> $GITHUB_ENV
      - name: Configure release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          echo "VERSION_NUMBER=${{ github.ref_name }}" >> $GITHUB_ENV
          echo "RELEASE_CHANNEL=stable" >> $GITHUB_ENV
      - name: Confirm release
        run: |
          curl -X 'POST' \
            'https://clangen.archanyhm.dev/api/v1/Update/Channels/${{ env.RELEASE_CHANNEL }}/Releases/${{ env.VERSION_NUMBER }}/Confirm' \
            -H 'X-API-Key: ${{ secrets.UPDATE_API_DEPLOY_KEY }}' \
            -H 'accept: */*'
